server:
  host: '127.0.0.1'
  port: 8080

logging:
  level: 'debug'

simulation: true

aws:
  region: 'eu-west-1'

database:
  url: 'http://localhost:8000'

# maximum amount of money that all users are allowed to invest
maxMoneyAmount: 1000