import { OrderType } from "../enums/order-type.enum";
import { OrderAction } from "../enums/order-action.enum";
import { Currency } from "../enums/trading-currencies.enum";

export type Order = {
    /** Internal ID to track the order */
    id: string,
    /** ID generated by the trading platform */
    externalId?: string,
    action: OrderAction
    type: OrderType,
    /** Example : if market symbol = BTC/EUR then originAsset = EUR */
    originAsset: Currency,
    /** Example : if market symbol = BTC/EUR then targetAsset = BTC */
    targetAsset: string,
    /** Example : if market symbol = BTC/EUR then amount is the number of BTC that we want to trade */
    amount: number,
    status?: 'open' | 'closed' | 'canceled';
    datetime?: string;
    /** Additional unparsed information that is returned from the API call to the trading platform */
    info?: unknown;
}