export type RedeemOrder = {
    /** ID generated by the trading platform */
    externalId: string,
    /** S, P, and F for "success", "pending", and "failure" */
    status: "S" | "P" | "F",
    targetAsset: string,
    /** Redemption token amount */
    redeemAmount: number,
    /** Redemption value in USDT */
    amount: number,
    timestamp: number
}