name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Check if strategies are running
      run: sh ./check_deploy.sh

    - name: Install libraries and compile
      run: npm ci && tsc

    - name: Run tests
      run: npm run test

    - name: Generate application zip
      run: sh ./compress_to_zip.sh MS.zip

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MS
        environment_name: Ms-env-2
        version_label: ${{ github.SHA }}
        region: eu-west-1
        deployment_package: MS.zip